### ISSUE TITLE
Native EEPROM library is not working with ATmega328

### ISSUE THREAD

**Issue by AyrtonEstrella** [MCUdude/MiniCore#50] opened 2018-04-02 20:56 UTC
Native EEPROM library is not working when I select the ATmega328 with any of its variants.

#include <EEPROM.h>
                    ^
compilation terminated.
exit status 1
Error compiling for board ATmega328.

<img width="301" alt="screen shot 2018-04-02 at 3 56 18 pm" src="https://user-images.githubusercontent.com/21128098/38215739-6a2aa166-368e-11e8-9910-84c9124ae132.png">

<img width="449" alt="screen shot 2018-04-02 at 3 57 28 pm" src="https://user-images.githubusercontent.com/21128098/38215814-953487dc-368e-11e8-9957-3709ec008820.png">

**Comment by per1234** [comment] 2018-04-02 21:19
Duplicate of https://github.com/MCUdude/MiniCore/issues/47

This issue has already been resolved in https://github.com/MCUdude/MiniCore/commit/a920f2c7654c992c3c163ad0870425b4352f5d6f but there has not been a release since that time. If you like, you can do a manual installation of the beta version of MiniCore, which will resolve this issue:
https://github.com/MCUdude/MiniCore#manual-installation

**Comment by MCUdude** [comment] 2018-04-28 23:56
EEPROM should now work with the latest boards manager version (v2.0.1)

**Closed by MCUdude** 2018-04-28 23:56 UTC
